// 游戏数据 - 由 spire-codex 生成
// 图片源配置 - 使用图床自定义域名
const IMAGE_BASE_URL = 'http://pic.wuqingzhe.cn/images';

const GAME_DATA = {
    cards: {
        "ABRASIVE": {"name": "磨蚀", "image": "cards/abrasive.png"},
        "ACCELERANT": {"name": "触媒", "image": "cards/accelerant.png"},
        "ACCURACY": {"name": "精准", "image": "cards/accuracy.png"},
        "ACROBATICS": {"name": "杂技", "image": "cards/acrobatics.png"},
        "ADAPTIVE_STRIKE": {"name": "适应打击", "image": "cards/adaptive_strike.png"},
        "ADRENALINE": {"name": "肾上腺素", "image": "cards/adrenaline.png"},
        "AFTERIMAGE": {"name": "余像", "image": "cards/afterimage.png"},
        "AFTERLIFE": {"name": "来生", "image": "cards/afterlife.png"},
        "AGGRESSION": {"name": "好勇斗狠", "image": "cards/aggression.png"},
        "ALCHEMIZE": {"name": "炼制药水", "image": "cards/alchemize.png"},
        "ALIGNMENT": {"name": "星位序列", "image": "cards/alignment.png"},
        "ALL_FOR_ONE": {"name": "万物一心", "image": "cards/all_for_one.png"},
        "ANGER": {"name": "愤怒", "image": "cards/anger.png"},
        "ANOINTED": {"name": "天选", "image": "cards/anointed.png"},
        "ANTICIPATE": {"name": "预判", "image": "cards/anticipate.png"},
        "APOTHEOSIS": {"name": "神化", "image": "cards/apotheosis.png"},
        "APPARITION": {"name": "灵体", "image": "cards/apparition.png"},
        "ARMAMENTS": {"name": "武装", "image": "cards/armaments.png"},
        "ARSENAL": {"name": "武器库", "image": "cards/arsenal.png"},
        "ASCENDERS_BANE": {"name": "进阶之灾", "image": "cards/ascenders_bane.png"},
        "ASHEN_STRIKE": {"name": "灰烬打击", "image": "cards/ashen_strike.png"},
        "ASSASSINATE": {"name": "刺杀", "image": "cards/assassinate.png"},
        "ASTRAL_PULSE": {"name": "星界脉冲", "image": "cards/astral_pulse.png"},
        "AUTOMATION": {"name": "自动化", "image": "cards/automation.png"},
        "BACKFLIP": {"name": "后空翻", "image": "cards/backflip.png"},
        "BACKSTAB": {"name": "背刺", "image": "cards/backstab.png"},
        "BAD_LUCK": {"name": "霉运", "image": "cards/bad_luck.png"},
        "BALL_LIGHTNING": {"name": "球状闪电", "image": "cards/ball_lightning.png"},
        "BANSHEES_CRY": {"name": "女妖之嚎", "image": "cards/banshees_cry.png"},
        "BARRAGE": {"name": "弹幕齐射", "image": "cards/barrage.png"},
        "BARRICADE": {"name": "壁垒", "image": "cards/barricade.png"},
        "BASH": {"name": "痛击", "image": "cards/bash.png"},
        "BATTLE_TRANCE": {"name": "战斗专注", "image": "cards/battle_trance.png"},
        "BEACON_OF_HOPE": {"name": "希望灯塔", "image": "cards/beacon_of_hope.png"},
        "BEAM_CELL": {"name": "光束射线", "image": "cards/beam_cell.png"},
        "BEAT_DOWN": {"name": "狠揍", "image": "cards/beat_down.png"},
        "BEAT_INTO_SHAPE": {"name": "锻打成型", "image": "cards/beat_into_shape.png"},
        "BECKON": {"name": "呼唤", "image": "cards/beckon.png"},
        "BEGONE": {"name": "下去！", "image": "cards/begone.png"},
        "BELIEVE_IN_YOU": {"name": "相信着你", "image": "cards/believe_in_you.png"},
        "BIASED_COGNITION": {"name": "偏差认知", "image": "cards/biased_cognition.png"},
        "BIG_BANG": {"name": "大爆炸", "image": "cards/big_bang.png"},
        "BLACK_HOLE": {"name": "黑洞", "image": "cards/black_hole.png"},
        "BLADE_DANCE": {"name": "刀刃之舞", "image": "cards/blade_dance.png"},
        "BLADE_OF_INK": {"name": "墨之刃", "image": "cards/blade_of_ink.png"},
        "BLIGHT_STRIKE": {"name": "荒疫打击", "image": "cards/blight_strike.png"},
        "BLOODLETTING": {"name": "放血", "image": "cards/bloodletting.png"},
        "BLOOD_WALL": {"name": "血墙", "image": "cards/blood_wall.png"},
        "BLUDGEON": {"name": "重锤", "image": "cards/bludgeon.png"},
        "BLUR": {"name": "残影", "image": "cards/blur.png"},
        "BODYGUARD": {"name": "护卫", "image": "cards/bodyguard.png"},
        "BODY_SLAM": {"name": "全身撞击", "image": "cards/body_slam.png"},
        "BOLAS": {"name": "流星锤", "image": "cards/bolas.png"},
        "BOMBARDMENT": {"name": "轰击", "image": "cards/bombardment.png"},
        "BONE_SHARDS": {"name": "碎骨", "image": "cards/bone_shards.png"},
        "BOOST_AWAY": {"name": "高速脱离", "image": "cards/boost_away.png"},
        "BOOT_SEQUENCE": {"name": "启动流程", "image": "cards/boot_sequence.png"},
        "BORROWED_TIME": {"name": "预借时间", "image": "cards/borrowed_time.png"},
        "BOUNCING_FLASK": {"name": "弹跳药瓶", "image": "cards/bouncing_flask.png"},
        "BRAND": {"name": "烙印", "image": "cards/brand.png"},
        "BREAK": {"name": "破击", "image": "cards/break.png"},
        "BREAKTHROUGH": {"name": "突破", "image": "cards/breakthrough.png"},
        "BRIGHTEST_FLAME": {"name": "至亮之焰", "image": "cards/brightest_flame.png"},
        "BUBBLE_BUBBLE": {"name": "咕嘟冒泡", "image": "cards/bubble_bubble.png"},
        "BUFFER": {"name": "缓冲", "image": "cards/buffer.png"},
        "BULK_UP": {"name": "暴涨", "image": "cards/bulk_up.png"},
        "BULLET_TIME": {"name": "子弹时间", "image": "cards/bullet_time.png"},
        "BULLY": {"name": "欺凌", "image": "cards/bully.png"},
        "BULWARK": {"name": "铸墙", "image": "cards/bulwark.png"},
        "BUNDLE_OF_JOY": {"name": "新生之喜", "image": "cards/bundle_of_joy.png"},
        "BURN": {"name": "灼伤", "image": "cards/burn.png"},
        "BURNING_PACT": {"name": "燃烧契约", "image": "cards/burning_pact.png"},
        "BURST": {"name": "爆发", "image": "cards/burst.png"},
        "BURY": {"name": "埋葬", "image": "cards/bury.png"},
        "BYRDONIS_EGG": {"name": "多尼斯异鸟蛋", "image": "cards/byrdonis_egg.png"},
        "BYRD_SWOOP": {"name": "异鸟扑击", "image": "cards/byrd_swoop.png"},
        "CALAMITY": {"name": "灾祸", "image": "cards/calamity.png"},
        "CALCIFY": {"name": "钙化", "image": "cards/calcify.png"},
        "CALCULATED_GAMBLE": {"name": "计算下注", "image": "cards/calculated_gamble.png"},
        "CALL_OF_THE_VOID": {"name": "虚空之唤", "image": "cards/call_of_the_void.png"},
        "CALTROPS": {"name": "铁蒺藜", "image": "cards/caltrops.png"},
        "CAPACITOR": {"name": "扩容", "image": "cards/capacitor.png"},
        "CAPTURE_SPIRIT": {"name": "捕捉灵魂", "image": "cards/capture_spirit.png"},
        "CASCADE": {"name": "倾泻", "image": "cards/cascade.png"},
        "CATASTROPHE": {"name": "横祸", "image": "cards/catastrophe.png"},
        "CELESTIAL_MIGHT": {"name": "天穹之力", "image": "cards/celestial_might.png"},
        "CHAOS": {"name": "混沌", "image": "cards/chaos.png"},
        "CHARGE": {"name": "冲锋！！", "image": "cards/charge.png"},
        "CHARGE_BATTERY": {"name": "充电", "image": "cards/charge_battery.png"},
        "CHILD_OF_THE_STARS": {"name": "群星之子", "image": "cards/child_of_the_stars.png"},
        "CHILL": {"name": "冰寒", "image": "cards/chill.png"},
        "CINDER": {"name": "余烬", "image": "cards/cinder.png"},
        "CLASH": {"name": "交锋", "image": "cards/clash.png"},
        "CLAW": {"name": "爪击", "image": "cards/claw.png"},
        "CLEANSE": {"name": "洁净", "image": "cards/cleanse.png"},
        "CLOAK_AND_DAGGER": {"name": "斗篷与匕首", "image": "cards/cloak_and_dagger.png"},
        "CLOAK_OF_STARS": {"name": "群星斗篷", "image": "cards/cloak_of_stars.png"},
        "CLUMSY": {"name": "笨拙", "image": "cards/clumsy.png"},
        "COLD_SNAP": {"name": "寒流", "image": "cards/cold_snap.png"},
        "COLLISION_COURSE": {"name": "碰撞轨迹", "image": "cards/collision_course.png"},
        "COLOSSUS": {"name": "巨像", "image": "cards/colossus.png"},
        "COMET": {"name": "彗星", "image": "cards/comet.png"},
        "COMPACT": {"name": "压缩", "image": "cards/compact.png"},
        "COMPILE_DRIVER": {"name": "编译冲击", "image": "cards/compile_driver.png"},
        "CONFLAGRATION": {"name": "焚烧", "image": "cards/conflagration.png"},
        "CONQUEROR": {"name": "征服者", "image": "cards/conqueror.png"},
        "CONSUMING_SHADOW": {"name": "吞噬暗影", "image": "cards/consuming_shadow.png"},
        "CONVERGENCE": {"name": "汇流", "image": "cards/convergence.png"},
        "COOLANT": {"name": "冷却剂", "image": "cards/coolant.png"},
        "COOLHEADED": {"name": "冷静头脑", "image": "cards/coolheaded.png"},
        "COORDINATE": {"name": "协同配合", "image": "cards/coordinate.png"},
        "CORROSIVE_WAVE": {"name": "腐蚀波", "image": "cards/corrosive_wave.png"},
        "CORRUPTION": {"name": "腐化", "image": "cards/corruption.png"},
        "COSMIC_INDIFFERENCE": {"name": "宇宙冷漠", "image": "cards/cosmic_indifference.png"},
        "COUNTDOWN": {"name": "倒数计时", "image": "cards/countdown.png"},
        "CRASH_LANDING": {"name": "迫降", "image": "cards/crash_landing.png"},
        "CREATIVE_AI": {"name": "创造性AI", "image": "cards/creative_ai.png"},
        "CRESCENT_SPEAR": {"name": "新月长矛", "image": "cards/crescent_spear.png"},
        "CRIMSON_MANTLE": {"name": "绯红披风", "image": "cards/crimson_mantle.png"},
        "CRUELTY": {"name": "残酷", "image": "cards/cruelty.png"},
        "CRUSH_UNDER": {"name": "下砸", "image": "cards/crush_under.png"},
        "CURSE_OF_THE_BELL": {"name": "铃铛的诅咒", "image": "cards/curse_of_the_bell.png"},
        "DAGGER_SPRAY": {"name": "匕首雨", "image": "cards/dagger_spray.png"},
        "DAGGER_THROW": {"name": "投掷匕首", "image": "cards/dagger_throw.png"},
        "DANSE_MACABRE": {"name": "死亡之舞", "image": "cards/danse_macabre.png"},
        "DARKNESS": {"name": "漆黑", "image": "cards/darkness.png"},
        "DARK_EMBRACE": {"name": "黑暗之拥", "image": "cards/dark_embrace.png"},
        "DARK_SHACKLES": {"name": "黑暗镣铐", "image": "cards/dark_shackles.png"},
        "DASH": {"name": "冲刺", "image": "cards/dash.png"},
        "DAZED": {"name": "晕眩", "image": "cards/dazed.png"},
        "DEADLY_POISON": {"name": "致命毒药", "image": "cards/deadly_poison.png"},
        "DEATHBRINGER": {"name": "死亡使者", "image": "cards/deathbringer.png"},
        "DEATHS_DOOR": {"name": "死亡之门", "image": "cards/deaths_door.png"},
        "DEATH_MARCH": {"name": "死亡行军", "image": "cards/death_march.png"},
        "DEBILITATE": {"name": "摧残", "image": "cards/debilitate.png"},
        "DEBRIS": {"name": "碎屑", "image": "cards/debris.png"},
        "DEBT": {"name": "债务", "image": "cards/debt.png"},
        "DECAY": {"name": "腐朽", "image": "cards/decay.png"},
        "DECISIONS_DECISIONS": {"name": "抉择，抉择", "image": "cards/decisions_decisions.png"},
        "DEFEND_DEFECT": {"name": "防御", "image": "cards/defend_defect.png"},
        "DEFEND_IRONCLAD": {"name": "防御", "image": "cards/defend_ironclad.png"},
        "DEFEND_NECROBINDER": {"name": "防御", "image": "cards/defend_necrobinder.png"},
        "DEFEND_REGENT": {"name": "防御", "image": "cards/defend_regent.png"},
        "DEFEND_SILENT": {"name": "防御", "image": "cards/defend_silent.png"},
        "DEFILE": {"name": "玷污", "image": "cards/defile.png"},
        "DEFLECT": {"name": "偏折", "image": "cards/deflect.png"},
        "DEFRAGMENT": {"name": "碎片整理", "image": "cards/defragment.png"},
        "DEFY": {"name": "违逆", "image": "cards/defy.png"},
        "DELAY": {"name": "拖延", "image": "cards/delay.png"},
        "DEMESNE": {"name": "领域", "image": "cards/demesne.png"},
        "DEMONIC_SHIELD": {"name": "恶魔护盾", "image": "cards/demonic_shield.png"},
        "DEMON_FORM": {"name": "恶魔形态", "image": "cards/demon_form.png"},
        "DEVASTATE": {"name": "葬送", "image": "cards/devastate.png"},
        "DEVOUR_LIFE": {"name": "吞噬生命", "image": "cards/devour_life.png"},
        "DIRGE": {"name": "挽歌", "image": "cards/dirge.png"},
        "DISCOVERY": {"name": "发现", "image": "cards/discovery.png"},
        "DISINTEGRATION": {"name": "瓦解", "image": "cards/disintegration.png"},
        "DISMANTLE": {"name": "拆卸", "image": "cards/dismantle.png"},
        "DISTRACTION": {"name": "声东击西", "image": "cards/distraction.png"},
        "DODGE_AND_ROLL": {"name": "闪躲翻滚", "image": "cards/dodge_and_roll.png"},
        "DOMINATE": {"name": "主宰", "image": "cards/dominate.png"},
        "DOUBLE_ENERGY": {"name": "双倍能量", "image": "cards/double_energy.png"},
        "DOUBT": {"name": "疑虑", "image": "cards/doubt.png"},
        "DRAIN_POWER": {"name": "能量汲取", "image": "cards/drain_power.png"},
        "DRAMATIC_ENTRANCE": {"name": "闪亮登场", "image": "cards/dramatic_entrance.png"},
        "DREDGE": {"name": "清淤", "image": "cards/dredge.png"},
        "DRUM_OF_BATTLE": {"name": "战鼓", "image": "cards/drum_of_battle.png"},
        "DUALCAST": {"name": "双重释放", "image": "cards/dualcast.png"},
        "DUAL_WIELD": {"name": "双持", "image": "cards/dual_wield.png"},
        "DYING_STAR": {"name": "星灭", "image": "cards/dying_star.png"},
        "ECHOING_SLASH": {"name": "回响斩击", "image": "cards/echoing_slash.png"},
        "ECHO_FORM": {"name": "回响形态", "image": "cards/echo_form.png"},
        "EIDOLON": {"name": "幻景", "image": "cards/eidolon.png"},
        "END_OF_DAYS": {"name": "末日降临", "image": "cards/end_of_days.png"},
        "ENERGY_SURGE": {"name": "能量涌动", "image": "cards/energy_surge.png"},
        "ENFEEBLING_TOUCH": {"name": "弱化之触", "image": "cards/enfeebling_touch.png"},
        "ENLIGHTENMENT": {"name": "开悟", "image": "cards/enlightenment.png"},
        "ENTHRALLED": {"name": "执迷", "image": "cards/enthralled.png"},
        "ENTRENCH": {"name": "巩固", "image": "cards/entrench.png"},
        "ENTROPY": {"name": "熵", "image": "cards/entropy.png"},
        "ENVENOM": {"name": "涂毒", "image": "cards/envenom.png"},
        "EQUILIBRIUM": {"name": "均衡", "image": "cards/equilibrium.png"},
        "ERADICATE": {"name": "根除", "image": "cards/eradicate.png"},
        "ESCAPE_PLAN": {"name": "逃脱计划", "image": "cards/escape_plan.png"},
        "ETERNAL_ARMOR": {"name": "永恒铠甲", "image": "cards/eternal_armor.png"},
        "EVIL_EYE": {"name": "邪眼", "image": "cards/evil_eye.png"},
        "EXPECT_A_FIGHT": {"name": "跃跃欲试", "image": "cards/expect_a_fight.png"},
        "EXPERTISE": {"name": "独门绝技", "image": "cards/expertise.png"},
        "EXPOSE": {"name": "暴露", "image": "cards/expose.png"},
        "EXTERMINATE": {"name": "杀灭", "image": "cards/exterminate.png"},
        "FALLING_STAR": {"name": "陨星", "image": "cards/falling_star.png"},
        "FAN_OF_KNIVES": {"name": "刀扇", "image": "cards/fan_of_knives.png"},
        "FASTEN": {"name": "勒紧", "image": "cards/fasten.png"},
        "FEAR": {"name": "恐惧", "image": "cards/fear.png"},
        "FEED": {"name": "狂宴", "image": "cards/feed.png"},
        "FEEDING_FRENZY": {"name": "疯狂进食", "image": "cards/feeding_frenzy.png"},
        "FEEL_NO_PAIN": {"name": "无惧疼痛", "image": "cards/feel_no_pain.png"},
        "FERAL": {"name": "野性", "image": "cards/feral.png"},
        "FETCH": {"name": "取回", "image": "cards/fetch.png"},
        "FIEND_FIRE": {"name": "恶魔之焰", "image": "cards/fiend_fire.png"},
        "FIGHT_ME": {"name": "与我一战！", "image": "cards/fight_me.png"},
        "FIGHT_THROUGH": {"name": "强撑", "image": "cards/fight_through.png"},
        "FINESSE": {"name": "妙计", "image": "cards/finesse.png"},
        "FINISHER": {"name": "终结技", "image": "cards/finisher.png"},
        "FISTICUFFS": {"name": "拳斗", "image": "cards/fisticuffs.png"},
        "FLAK_CANNON": {"name": "散射炮", "image": "cards/flak_cannon.png"},
        "FLAME_BARRIER": {"name": "火焰屏障", "image": "cards/flame_barrier.png"},
        "FLANKING": {"name": "夹击", "image": "cards/flanking.png"},
        "FLASH_OF_STEEL": {"name": "亮剑", "image": "cards/flash_of_steel.png"},
        "FLATTEN": {"name": "重压", "image": "cards/flatten.png"},
        "FLECHETTES": {"name": "飞镖", "image": "cards/flechettes.png"},
        "FLICK_FLACK": {"name": "翻越撑击", "image": "cards/flick_flack.png"},
        "FOCUSED_STRIKE": {"name": "集中打击", "image": "cards/focused_strike.png"},
        "FOLLOW_THROUGH": {"name": "跟进", "image": "cards/follow_through.png"},
        "FOLLY": {"name": "愚行", "image": "cards/folly.png"},
        "FOOTWORK": {"name": "灵动步法", "image": "cards/footwork.png"},
        "FORBIDDEN_GRIMOIRE": {"name": "禁忌魔典", "image": "cards/forbidden_grimoire.png"},
        "FOREGONE_CONCLUSION": {"name": "既定事项", "image": "cards/foregone_conclusion.png"},
        "FORGOTTEN_RITUAL": {"name": "被遗忘的仪式", "image": "cards/forgotten_ritual.png"},
        "FRANTIC_ESCAPE": {"name": "狂乱逃离", "image": "cards/frantic_escape.png"},
        "FRIENDSHIP": {"name": "友谊", "image": "cards/friendship.png"},
        "FTL": {"name": "超越光速", "image": "cards/ftl.png"},
        "FUEL": {"name": "燃料", "image": "cards/fuel.png"},
        "FURNACE": {"name": "熔炉", "image": "cards/furnace.png"},
        "FUSION": {"name": "聚变", "image": "cards/fusion.png"},
        "GAMMA_BLAST": {"name": "伽马爆破", "image": "cards/gamma_blast.png"},
        "GANG_UP": {"name": "群起攻之", "image": "cards/gang_up.png"},
        "GATHER_LIGHT": {"name": "收集光辉", "image": "cards/gather_light.png"},
        "GENESIS": {"name": "创世纪", "image": "cards/genesis.png"},
        "GENETIC_ALGORITHM": {"name": "遗传算法", "image": "cards/genetic_algorithm.png"},
        "GIANT_ROCK": {"name": "巨石", "image": "cards/giant_rock.png"},
        "GLACIER": {"name": "冰川", "image": "cards/glacier.png"},
        "GLASSWORK": {"name": "玻璃工艺", "image": "cards/glasswork.png"},
        "GLIMMER": {"name": "微光", "image": "cards/glimmer.png"},
        "GLIMPSE_BEYOND": {"name": "彼岸一瞥", "image": "cards/glimpse_beyond.png"},
        "GLITTERSTREAM": {"name": "流光溢彩", "image": "cards/glitterstream.png"},
        "GLOW": {"name": "辉光", "image": "cards/glow.png"},
        "GOLD_AXE": {"name": "金斧", "image": "cards/gold_axe.png"},
        "GO_FOR_THE_EYES": {"name": "眼部攻击", "image": "cards/go_for_the_eyes.png"},
        "GRAND_FINALE": {"name": "华丽收场", "image": "cards/grand_finale.png"},
        "GRAPPLE": {"name": "擒拿", "image": "cards/grapple.png"},
        "GRAVEBLAST": {"name": "坟冢爆射", "image": "cards/graveblast.png"},
        "GRAVE_WARDEN": {"name": "守墓人", "image": "cards/grave_warden.png"},
        "GREED": {"name": "贪婪", "image": "cards/greed.png"},
        "GUARDS": {"name": "护驾！！！", "image": "cards/guards.png"},
        "GUIDING_STAR": {"name": "引导之星", "image": "cards/guiding_star.png"},
        "GUILTY": {"name": "愧疚", "image": "cards/guilty.png"},
        "GUNK_UP": {"name": "污秽攻击", "image": "cards/gunk_up.png"},
        "HAILSTORM": {"name": "冰雹风暴", "image": "cards/hailstorm.png"},
        "HAMMER_TIME": {"name": "锤子时间", "image": "cards/hammer_time.png"},
        "HAND_OF_GREED": {"name": "贪婪之手", "image": "cards/hand_of_greed.png"},
        "HAND_TRICK": {"name": "手上技法", "image": "cards/hand_trick.png"},
        "HANG": {"name": "吊杀", "image": "cards/hang.png"},
        "HAUNT": {"name": "纠缠", "image": "cards/haunt.png"},
        "HAVOC": {"name": "破灭", "image": "cards/havoc.png"},
        "HAZE": {"name": "迷雾", "image": "cards/haze.png"},
        "HEADBUTT": {"name": "头槌", "image": "cards/headbutt.png"},
        "HEAVENLY_DRILL": {"name": "天际钻头", "image": "cards/heavenly_drill.png"},
        "HEGEMONY": {"name": "霸权", "image": "cards/hegemony.png"},
        "HEIRLOOM_HAMMER": {"name": "传承之锤", "image": "cards/heirloom_hammer.png"},
        "HELIX_DRILL": {"name": "螺旋钻击", "image": "cards/helix_drill.png"},
        "HELLO_WORLD": {"name": "你好世界", "image": "cards/hello_world.png"},
        "HELLRAISER": {"name": "地狱狂徒", "image": "cards/hellraiser.png"},
        "HEMOKINESIS": {"name": "御血术", "image": "cards/hemokinesis.png"},
        "HIDDEN_CACHE": {"name": "隐秘藏品", "image": "cards/hidden_cache.png"},
        "HIDDEN_DAGGERS": {"name": "隐秘匕首", "image": "cards/hidden_daggers.png"},
        "HIDDEN_GEM": {"name": "未掘宝石", "image": "cards/hidden_gem.png"},
        "HIGH_FIVE": {"name": "击掌", "image": "cards/high_five.png"},
        "HOLOGRAM": {"name": "全息影像", "image": "cards/hologram.png"},
        "HOTFIX": {"name": "热修复", "image": "cards/hotfix.png"},
        "HOWL_FROM_BEYOND": {"name": "彼岸咆哮", "image": "cards/howl_from_beyond.png"},
        "HUDDLE_UP": {"name": "抱团", "image": "cards/huddle_up.png"},
        "HYPERBEAM": {"name": "超能光束", "image": "cards/hyperbeam.png"},
        "ICE_LANCE": {"name": "冰之长枪", "image": "cards/ice_lance.png"},
        "IGNITION": {"name": "引火", "image": "cards/ignition.png"},
        "IMPATIENCE": {"name": "急躁", "image": "cards/impatience.png"},
        "IMPERVIOUS": {"name": "岿然不动", "image": "cards/impervious.png"},
        "INFECTION": {"name": "感染", "image": "cards/infection.png"},
        "INFERNAL_BLADE": {"name": "地狱之刃", "image": "cards/infernal_blade.png"},
        "INFERNO": {"name": "狱火", "image": "cards/inferno.png"},
        "INFINITE_BLADES": {"name": "无尽刀刃", "image": "cards/infinite_blades.png"},
        "INFLAME": {"name": "燃烧", "image": "cards/inflame.png"},
        "INJURY": {"name": "受伤", "image": "cards/injury.png"},
        "INTERCEPT": {"name": "拦截", "image": "cards/intercept.png"},
        "INVOKE": {"name": "唤起", "image": "cards/invoke.png"},
        "IRON_WAVE": {"name": "铁斩波", "image": "cards/iron_wave.png"},
        "ITERATION": {"name": "迭代", "image": "cards/iteration.png"},
        "I_AM_INVINCIBLE": {"name": "所向无敌", "image": "cards/i_am_invincible.png"},
        "JACKPOT": {"name": "大奖", "image": "cards/jackpot.png"},
        "JACK_OF_ALL_TRADES": {"name": "花样百出", "image": "cards/jack_of_all_trades.png"},
        "JUGGERNAUT": {"name": "势不可当", "image": "cards/juggernaut.png"},
        "JUGGLING": {"name": "杂耍", "image": "cards/juggling.png"},
        "KINGLY_KICK": {"name": "王者之踢", "image": "cards/kingly_kick.png"},
        "KINGLY_PUNCH": {"name": "王者之拳", "image": "cards/kingly_punch.png"},
        "KNIFE_TRAP": {"name": "刀刃陷阱", "image": "cards/knife_trap.png"},
        "KNOCKDOWN": {"name": "击倒", "image": "cards/knockdown.png"},
        "KNOCKOUT_BLOW": {"name": "决胜一击", "image": "cards/knockout_blow.png"},
        "KNOW_THY_PLACE": {"name": "何人僭越", "image": "cards/know_thy_place.png"},
        "LANTERN_KEY": {"name": "灯火钥匙", "image": "cards/lantern_key.png"},
        "LARGESSE": {"name": "慷慨捐助", "image": "cards/largesse.png"},
        "LEADING_STRIKE": {"name": "先制打击", "image": "cards/leading_strike.png"},
        "LEAP": {"name": "飞跃", "image": "cards/leap.png"},
        "LEGION_OF_BONE": {"name": "骸骨军团", "image": "cards/legion_of_bone.png"},
        "LEG_SWEEP": {"name": "扫腿", "image": "cards/leg_sweep.png"},
        "LETHALITY": {"name": "致死性", "image": "cards/lethality.png"},
        "LIFT": {"name": "托举", "image": "cards/lift.png"},
        "LIGHTNING_ROD": {"name": "引雷针", "image": "cards/lightning_rod.png"},
        "LOOP": {"name": "循环", "image": "cards/loop.png"},
        "LUMINESCE": {"name": "冷光", "image": "cards/luminesce.png"},
        "LUNAR_BLAST": {"name": "月面射击", "image": "cards/lunar_blast.png"},
        "MACHINE_LEARNING": {"name": "机器学习", "image": "cards/machine_learning.png"},
        "MAD_SCIENCE": {"name": "疯狂科学", "image": ""},
        "MAKE_IT_SO": {"name": "如此甚好", "image": "cards/make_it_so.png"},
        "MALAISE": {"name": "萎靡", "image": "cards/malaise.png"},
        "MANGLE": {"name": "凌虐", "image": "cards/mangle.png"},
        "MANIFEST_AUTHORITY": {"name": "君权自授", "image": "cards/manifest_authority.png"},
        "MASTER_OF_STRATEGY": {"name": "战略大师", "image": "cards/master_of_strategy.png"},
        "MASTER_PLANNER": {"name": "谋划专家", "image": "cards/master_planner.png"},
        "MAUL": {"name": "撕咬", "image": "cards/maul.png"},
        "MAYHEM": {"name": "乱战", "image": "cards/mayhem.png"},
        "MELANCHOLY": {"name": "忧郁", "image": "cards/melancholy.png"},
        "MEMENTO_MORI": {"name": "铭记死亡", "image": "cards/memento_mori.png"},
        "METAMORPHOSIS": {"name": "羽化", "image": "cards/metamorphosis.png"},
        "METEOR_SHOWER": {"name": "流星雨", "image": "cards/meteor_shower.png"},
        "METEOR_STRIKE": {"name": "陨石打击", "image": "cards/meteor_strike.png"},
        "MIMIC": {"name": "拟态", "image": "cards/mimic.png"},
        "MIND_BLAST": {"name": "心灵震慑", "image": "cards/mind_blast.png"},
        "MIND_ROT": {"name": "心灵腐化", "image": "cards/mind_rot.png"},
        "MINION_DIVE_BOMB": {"name": "仆从俯冲", "image": "cards/minion_dive_bomb.png"},
        "MINION_SACRIFICE": {"name": "仆从捐躯", "image": "cards/minion_sacrifice.png"},
        "MINION_STRIKE": {"name": "仆从打击", "image": "cards/minion_strike.png"},
        "MIRAGE": {"name": "蜃景", "image": "cards/mirage.png"},
        "MISERY": {"name": "苦难", "image": "cards/misery.png"},
        "MODDED": {"name": "模组改造", "image": "cards/modded.png"},
        "MOLTEN_FIST": {"name": "熔融之拳", "image": "cards/molten_fist.png"},
        "MOMENTUM_STRIKE": {"name": "趁势打击", "image": "cards/momentum_strike.png"},
        "MONARCHS_GAZE": {"name": "王之凝视", "image": "cards/monarchs_gaze.png"},
        "MONOLOGUE": {"name": "独白", "image": "cards/monologue.png"},
        "MULTI_CAST": {"name": "多重释放", "image": "cards/multi_cast.png"},
        "MURDER": {"name": "谋杀", "image": "cards/murder.png"},
        "NECRO_MASTERY": {"name": "亡灵精通", "image": "cards/necro_mastery.png"},
        "NEGATIVE_PULSE": {"name": "负能量脉冲", "image": "cards/negative_pulse.png"},
        "NEOWS_FURY": {"name": "涅奥之怒", "image": "cards/neows_fury.png"},
        "NEUROSURGE": {"name": "精神过载", "image": "cards/neurosurge.png"},
        "NEUTRALIZE": {"name": "中和", "image": "cards/neutralize.png"},
        "NEUTRON_AEGIS": {"name": "中子护盾", "image": "cards/neutron_aegis.png"},
        "NIGHTMARE": {"name": "夜魇", "image": "cards/nightmare.png"},
        "NORMALITY": {"name": "凡庸", "image": "cards/normality.png"},
        "NOSTALGIA": {"name": "怀旧", "image": "cards/nostalgia.png"},
        "NOXIOUS_FUMES": {"name": "毒雾", "image": "cards/noxious_fumes.png"},
        "NO_ESCAPE": {"name": "无处可逃", "image": "cards/no_escape.png"},
        "NULL": {"name": "空无", "image": "cards/null.png"},
        "OBLIVION": {"name": "湮灭", "image": "cards/oblivion.png"},
        "OFFERING": {"name": "祭品", "image": "cards/offering.png"},
        "OMNISLICE": {"name": "万向斩", "image": "cards/omnislice.png"},
        "ONE_TWO_PUNCH": {"name": "连环拳", "image": "cards/one_two_punch.png"},
        "ORBIT": {"name": "环绕轨道", "image": "cards/orbit.png"},
        "OUTBREAK": {"name": "毒性爆发", "image": "cards/outbreak.png"},
        "OUTMANEUVER": {"name": "抢占先机", "image": "cards/outmaneuver.png"},
        "OVERCLOCK": {"name": "超频", "image": "cards/overclock.png"},
        "PACTS_END": {"name": "契约终结", "image": "cards/pacts_end.png"},
        "PAGESTORM": {"name": "书页风暴", "image": "cards/pagestorm.png"},
        "PALE_BLUE_DOT": {"name": "暗淡蓝点", "image": "cards/pale_blue_dot.png"},
        "PANACHE": {"name": "神气制胜", "image": "cards/panache.png"},
        "PANIC_BUTTON": {"name": "应急按钮", "image": "cards/panic_button.png"},
        "PARRY": {"name": "招架", "image": "cards/parry.png"},
        "PARSE": {"name": "领会", "image": "cards/parse.png"},
        "PARTICLE_WALL": {"name": "粒子墙", "image": "cards/particle_wall.png"},
        "PATTER": {"name": "星星点点", "image": "cards/patter.png"},
        "PECK": {"name": "啄击", "image": "cards/peck.png"},
        "PERFECTED_STRIKE": {"name": "完美打击", "image": "cards/perfected_strike.png"},
        "PHANTOM_BLADES": {"name": "幻影之刃", "image": "cards/phantom_blades.png"},
        "PHOTON_CUT": {"name": "光子切割", "image": "cards/photon_cut.png"},
        "PIERCING_WAIL": {"name": "尖啸", "image": "cards/piercing_wail.png"},
        "PILLAGE": {"name": "劫掠", "image": "cards/pillage.png"},
        "PILLAR_OF_CREATION": {"name": "创世之柱", "image": "cards/pillar_of_creation.png"},
        "PINPOINT": {"name": "精密瞄准", "image": "cards/pinpoint.png"},
        "POISONED_STAB": {"name": "带毒刺击", "image": "cards/poisoned_stab.png"},
        "POKE": {"name": "戳击", "image": "cards/poke.png"},
        "POMMEL_STRIKE": {"name": "剑柄打击", "image": "cards/pommel_strike.png"},
        "POOR_SLEEP": {"name": "睡眠不佳", "image": "cards/poor_sleep.png"},
        "POUNCE": {"name": "猛扑", "image": "cards/pounce.png"},
        "PRECISE_CUT": {"name": "精确切击", "image": "cards/precise_cut.png"},
        "PREDATOR": {"name": "猎杀者", "image": "cards/predator.png"},
        "PREPARED": {"name": "早有准备", "image": "cards/prepared.png"},
        "PREP_TIME": {"name": "准备时间", "image": "cards/prep_time.png"},
        "PRIMAL_FORCE": {"name": "原始力量", "image": "cards/primal_force.png"},
        "PRODUCTION": {"name": "生产制造", "image": "cards/production.png"},
        "PROLONG": {"name": "延伸", "image": "cards/prolong.png"},
        "PROPHESIZE": {"name": "预言", "image": "cards/prophesize.png"},
        "PROTECTOR": {"name": "守护者", "image": "cards/protector.png"},
        "PROWESS": {"name": "非凡技艺", "image": "cards/prowess.png"},
        "PULL_AGGRO": {"name": "吸引仇恨", "image": "cards/pull_aggro.png"},
        "PULL_FROM_BELOW": {"name": "亡魂牵引", "image": "cards/pull_from_below.png"},
        "PURITY": {"name": "净化", "image": "cards/purity.png"},
        "PUTREFY": {"name": "腐败", "image": "cards/putrefy.png"},
        "PYRE": {"name": "薪火之源", "image": "cards/pyre.png"},
        "QUADCAST": {"name": "四重释放", "image": "cards/quadcast.png"},
        "QUASAR": {"name": "类星体", "image": "cards/quasar.png"},
        "RADIATE": {"name": "辐射", "image": "cards/radiate.png"},
        "RAGE": {"name": "狂怒", "image": "cards/rage.png"},
        "RAINBOW": {"name": "彩虹", "image": "cards/rainbow.png"},
        "RALLY": {"name": "集结", "image": "cards/rally.png"},
        "RAMPAGE": {"name": "暴走", "image": "cards/rampage.png"},
        "RATTLE": {"name": "猛晃", "image": "cards/rattle.png"},
        "REANIMATE": {"name": "死者苏生", "image": "cards/reanimate.png"},
        "REAP": {"name": "收割", "image": "cards/reap.png"},
        "REAPER_FORM": {"name": "死神形态", "image": "cards/reaper_form.png"},
        "REAVE": {"name": "剥夺", "image": "cards/reave.png"},
        "REBOOT": {"name": "重启", "image": "cards/reboot.png"},
        "REBOUND": {"name": "弹回", "image": "cards/rebound.png"},
        "REFINE_BLADE": {"name": "淬炼刀刃", "image": "cards/refine_blade.png"},
        "REFLECT": {"name": "倒映", "image": "cards/reflect.png"},
        "REFLEX": {"name": "本能反应", "image": "cards/reflex.png"},
        "REFRACT": {"name": "折射", "image": "cards/refract.png"},
        "REGRET": {"name": "悔恨", "image": "cards/regret.png"},
        "RELAX": {"name": "放松", "image": "cards/relax.png"},
        "REND": {"name": "撕碎", "image": "cards/rend.png"},
        "RESONANCE": {"name": "共鸣", "image": "cards/resonance.png"},
        "RESTLESSNESS": {"name": "心神不宁", "image": "cards/restlessness.png"},
        "RICOCHET": {"name": "连续反弹", "image": "cards/ricochet.png"},
        "RIGHT_HAND_HAND": {"name": "得力助手", "image": "cards/right_hand_hand.png"},
        "RIP_AND_TEAR": {"name": "狂乱撕扯", "image": "cards/rip_and_tear.png"},
        "ROCKET_PUNCH": {"name": "火箭飞拳", "image": "cards/rocket_punch.png"},
        "ROLLING_BOULDER": {"name": "滚石", "image": "cards/rolling_boulder.png"},
        "ROYALTIES": {"name": "王国资产", "image": "cards/royalties.png"},
        "ROYAL_GAMBLE": {"name": "胜券在王", "image": "cards/royal_gamble.png"},
        "RUPTURE": {"name": "撕裂", "image": "cards/rupture.png"},
        "SACRIFICE": {"name": "牺牲", "image": "cards/sacrifice.png"},
        "SALVO": {"name": "箭雨", "image": "cards/salvo.png"},
        "SCAVENGE": {"name": "再利用", "image": "cards/scavenge.png"},
        "SCOURGE": {"name": "鞭打", "image": "cards/scourge.png"},
        "SCRAPE": {"name": "刮削", "image": "cards/scrape.png"},
        "SCRAWL": {"name": "潦草急就", "image": "cards/scrawl.png"},
        "SCULPTING_STRIKE": {"name": "雕琢打击", "image": "cards/sculpting_strike.png"},
        "SEANCE": {"name": "降灵", "image": "cards/seance.png"},
        "SECOND_WIND": {"name": "重振精神", "image": "cards/second_wind.png"},
        "SECRET_TECHNIQUE": {"name": "秘密技法", "image": "cards/secret_technique.png"},
        "SECRET_WEAPON": {"name": "秘密武器", "image": "cards/secret_weapon.png"},
        "SEEKER_STRIKE": {"name": "探寻打击", "image": "cards/seeker_strike.png"},
        "SEEKING_EDGE": {"name": "追踪之刃", "image": "cards/seeking_edge.png"},
        "SENTRY_MODE": {"name": "哨卫模式", "image": "cards/sentry_mode.png"},
        "SERPENT_FORM": {"name": "群蛇形态", "image": "cards/serpent_form.png"},
        "SETUP_STRIKE": {"name": "预备打击", "image": "cards/setup_strike.png"},
        "SEVEN_STARS": {"name": "七星", "image": "cards/seven_stars.png"},
        "SEVERANCE": {"name": "切断", "image": "cards/severance.png"},
        "SHADOWMELD": {"name": "融入暗影", "image": "cards/shadowmeld.png"},
        "SHADOW_SHIELD": {"name": "暗影之盾", "image": "cards/shadow_shield.png"},
        "SHADOW_STEP": {"name": "暗影步", "image": "cards/shadow_step.png"},
        "SHAME": {"name": "羞耻", "image": "cards/shame.png"},
        "SHARED_FATE": {"name": "命运同担", "image": "cards/shared_fate.png"},
        "SHATTER": {"name": "打碎", "image": "cards/shatter.png"},
        "SHINING_STRIKE": {"name": "明耀打击", "image": "cards/shining_strike.png"},
        "SHIV": {"name": "小刀", "image": "cards/shiv.png"},
        "SHOCKWAVE": {"name": "震荡波", "image": "cards/shockwave.png"},
        "SHROUD": {"name": "厄运之衣", "image": "cards/shroud.png"},
        "SHRUG_IT_OFF": {"name": "耸肩无视", "image": "cards/shrug_it_off.png"},
        "SIC_EM": {"name": "紧追不放", "image": "cards/sic_em.png"},
        "SIGNAL_BOOST": {"name": "信号增强", "image": "cards/signal_boost.png"},
        "SKEWER": {"name": "串刺", "image": "cards/skewer.png"},
        "SKIM": {"name": "快速检索", "image": "cards/skim.png"},
        "SLEIGHT_OF_FLESH": {"name": "血肉戏法", "image": "cards/sleight_of_flesh.png"},
        "SLICE": {"name": "切割", "image": "cards/slice.png"},
        "SLIMED": {"name": "黏液", "image": "cards/slimed.png"},
        "SLOTH": {"name": "懒惰", "image": "cards/sloth.png"},
        "SMOKESTACK": {"name": "烟囱", "image": "cards/smokestack.png"},
        "SNAKEBITE": {"name": "蛇咬", "image": "cards/snakebite.png"},
        "SNAP": {"name": "抓取", "image": "cards/snap.png"},
        "SNEAKY": {"name": "鬼祟", "image": "cards/sneaky.png"},
        "SOLAR_STRIKE": {"name": "太阳打击", "image": "cards/solar_strike.png"},
        "SOOT": {"name": "煤灰", "image": "cards/soot.png"},
        "SOUL": {"name": "灵魂", "image": "cards/soul.png"},
        "SOUL_STORM": {"name": "灵魂风暴", "image": "cards/soul_storm.png"},
        "SOVEREIGN_BLADE": {"name": "君王之剑", "image": "cards/sovereign_blade.png"},
        "SOW": {"name": "播种", "image": "cards/sow.png"},
        "SPECTRUM_SHIFT": {"name": "光谱偏移", "image": "cards/spectrum_shift.png"},
        "SPEEDSTER": {"name": "速行者", "image": "cards/speedster.png"},
        "SPINNER": {"name": "旋转工艺", "image": "cards/spinner.png"},
        "SPIRIT_OF_ASH": {"name": "灰烬之灵", "image": "cards/spirit_of_ash.png"},
        "SPITE": {"name": "怨恨", "image": "cards/spite.png"},
        "SPLASH": {"name": "飞溅", "image": "cards/splash.png"},
        "SPOILS_MAP": {"name": "藏宝图", "image": "cards/spoils_map.png"},
        "SPOILS_OF_BATTLE": {"name": "战利品", "image": "cards/spoils_of_battle.png"},
        "SPORE_MIND": {"name": "孢子心灵", "image": "cards/spore_mind.png"},
        "SPUR": {"name": "增生", "image": "cards/spur.png"},
        "SQUASH": {"name": "压扁", "image": "cards/squash.png"},
        "SQUEEZE": {"name": "榨取", "image": "cards/squeeze.png"},
        "STACK": {"name": "堆栈", "image": "cards/stack.png"},
        "STAMPEDE": {"name": "惊逃", "image": "cards/stampede.png"},
        "STARDUST": {"name": "星尘", "image": "cards/stardust.png"},
        "STOKE": {"name": "添柴", "image": "cards/stoke.png"},
        "STOMP": {"name": "踩踏", "image": "cards/stomp.png"},
        "STONE_ARMOR": {"name": "岩石铠甲", "image": "cards/stone_armor.png"},
        "STORM": {"name": "雷暴", "image": "cards/storm.png"},
        "STORM_OF_STEEL": {"name": "钢铁风暴", "image": "cards/storm_of_steel.png"},
        "STRANGLE": {"name": "紧勒", "image": "cards/strangle.png"},
        "STRATAGEM": {"name": "计策", "image": "cards/stratagem.png"},
        "STRIKE_DEFECT": {"name": "打击", "image": "cards/strike_defect.png"},
        "STRIKE_IRONCLAD": {"name": "打击", "image": "cards/strike_ironclad.png"},
        "STRIKE_NECROBINDER": {"name": "打击", "image": "cards/strike_necrobinder.png"},
        "STRIKE_REGENT": {"name": "打击", "image": "cards/strike_regent.png"},
        "STRIKE_SILENT": {"name": "打击", "image": "cards/strike_silent.png"},
        "SUBROUTINE": {"name": "子程序", "image": "cards/subroutine.png"},
        "SUCKER_PUNCH": {"name": "突然一拳", "image": "cards/sucker_punch.png"},
        "SUMMON_FORTH": {"name": "征召上前", "image": "cards/summon_forth.png"},
        "SUNDER": {"name": "分离", "image": "cards/sunder.png"},
        "SUPERCRITICAL": {"name": "超临界态", "image": "cards/supercritical.png"},
        "SUPERMASSIVE": {"name": "超质量体", "image": "cards/supermassive.png"},
        "SUPPRESS": {"name": "压制", "image": "cards/suppress.png"},
        "SURVIVOR": {"name": "生存者", "image": "cards/survivor.png"},
        "SWEEPING_BEAM": {"name": "扫荡射线", "image": "cards/sweeping_beam.png"},
        "SWEEPING_GAZE": {"name": "扫荡凝视", "image": "cards/sweeping_gaze.png"},
        "SWORD_BOOMERANG": {"name": "飞剑回旋镖", "image": "cards/sword_boomerang.png"},
        "SWORD_SAGE": {"name": "剑圣", "image": "cards/sword_sage.png"},
        "SYNCHRONIZE": {"name": "同步", "image": "cards/synchronize.png"},
        "SYNTHESIS": {"name": "人工合成", "image": "cards/synthesis.png"},
        "TACTICIAN": {"name": "战术大师", "image": "cards/tactician.png"},
        "TAG_TEAM": {"name": "双打组合", "image": "cards/tag_team.png"},
        "TANK": {"name": "肉盾", "image": "cards/tank.png"},
        "TAUNT": {"name": "挑衅", "image": "cards/taunt.png"},
        "TEAR_ASUNDER": {"name": "扯碎", "image": "cards/tear_asunder.png"},
        "TEMPEST": {"name": "暴风雨", "image": "cards/tempest.png"},
        "TERRAFORMING": {"name": "地形改造", "image": "cards/terraforming.png"},
        "TESLA_COIL": {"name": "特斯拉线圈", "image": "cards/tesla_coil.png"},
        "THE_BOMB": {"name": "炸弹", "image": "cards/the_bomb.png"},
        "THE_GAMBIT": {"name": "孤注一掷", "image": "cards/the_gambit.png"},
        "THE_HUNT": {"name": "狩猎", "image": "cards/the_hunt.png"},
        "THE_SCYTHE": {"name": "巨镰", "image": "cards/the_scythe.png"},
        "THE_SEALED_THRONE": {"name": "封印王座", "image": "cards/the_sealed_throne.png"},
        "THE_SMITH": {"name": "铸剑者", "image": "cards/the_smith.png"},
        "THINKING_AHEAD": {"name": "深谋远虑", "image": "cards/thinking_ahead.png"},
        "THRASH": {"name": "痛殴", "image": "cards/thrash.png"},
        "THRUMMING_HATCHET": {"name": "无休手斧", "image": "cards/thrumming_hatchet.png"},
        "THUNDER": {"name": "雷霆", "image": "cards/thunder.png"},
        "THUNDERCLAP": {"name": "闪电霹雳", "image": "cards/thunderclap.png"},
        "TIMES_UP": {"name": "大限已至", "image": "cards/times_up.png"},
        "TOOLS_OF_THE_TRADE": {"name": "必备工具", "image": "cards/tools_of_the_trade.png"},
        "TORIC_TOUGHNESS": {"name": "坚韧之环", "image": "cards/toric_toughness.png"},
        "TOXIC": {"name": "毒素", "image": "cards/toxic.png"},
        "TRACKING": {"name": "跟踪", "image": "cards/tracking.png"},
        "TRANSFIGURE": {"name": "重构", "image": "cards/transfigure.png"},
        "TRASH_TO_TREASURE": {"name": "化废为宝", "image": "cards/trash_to_treasure.png"},
        "TREMBLE": {"name": "战栗", "image": "cards/tremble.png"},
        "TRUE_GRIT": {"name": "坚毅", "image": "cards/true_grit.png"},
        "TURBO": {"name": "内核加速", "image": "cards/turbo.png"},
        "TWIN_STRIKE": {"name": "双重打击", "image": "cards/twin_strike.png"},
        "TYRANNY": {"name": "暴政", "image": "cards/tyranny.png"},
        "ULTIMATE_DEFEND": {"name": "究极防御", "image": "cards/ultimate_defend.png"},
        "ULTIMATE_STRIKE": {"name": "究极打击", "image": "cards/ultimate_strike.png"},
        "UNDEATH": {"name": "不死", "image": "cards/undeath.png"},
        "UNLEASH": {"name": "出击", "image": "cards/unleash.png"},
        "UNMOVABLE": {"name": "坚定不移", "image": "cards/unmovable.png"},
        "UNRELENTING": {"name": "无情猛攻", "image": "cards/unrelenting.png"},
        "UNTOUCHABLE": {"name": "触不可及", "image": "cards/untouchable.png"},
        "UPPERCUT": {"name": "上勾拳", "image": "cards/uppercut.png"},
        "UPROAR": {"name": "骚动", "image": "cards/uproar.png"},
        "UP_MY_SLEEVE": {"name": "袖里乾坤", "image": "cards/up_my_sleeve.png"},
        "VEILPIERCER": {"name": "刺破帷幕", "image": "cards/veilpiercer.png"},
        "VENERATE": {"name": "崇拜", "image": "cards/venerate.png"},
        "VICIOUS": {"name": "凶恶", "image": "cards/vicious.png"},
        "VOID": {"name": "虚空", "image": "cards/void.png"},
        "VOID_FORM": {"name": "虚空形态", "image": "cards/void_form.png"},
        "VOLLEY": {"name": "连射", "image": "cards/volley.png"},
        "VOLTAIC": {"name": "电流相生", "image": "cards/voltaic.png"},
        "WASTE_AWAY": {"name": "衰朽", "image": "cards/waste_away.png"},
        "WELL_LAID_PLANS": {"name": "计划妥当", "image": "cards/well_laid_plans.png"},
        "WHIRLWIND": {"name": "旋风斩", "image": "cards/whirlwind.png"},
        "WHISTLE": {"name": "吹哨", "image": "cards/whistle.png"},
        "WHITE_NOISE": {"name": "白噪音", "image": "cards/white_noise.png"},
        "WISH": {"name": "许愿", "image": "cards/wish.png"},
        "WISP": {"name": "鬼火", "image": "cards/wisp.png"},
        "WOUND": {"name": "伤口", "image": "cards/wound.png"},
        "WRAITH_FORM": {"name": "幽魂形态", "image": "cards/wraith_form.png"},
        "WRITHE": {"name": "苦恼", "image": "cards/writhe.png"},
        "WROUGHT_IN_WAR": {"name": "战火铸就", "image": "cards/wrought_in_war.png"},
        "ZAP": {"name": "电击", "image": "cards/zap.png"}
    },
    relics: {
        "AKABEKO": {"name": "赤牛", "image": "relics/akabeko.png"},
        "ALCHEMICAL_COFFER": {"name": "炼金箱", "image": "relics/alchemical_coffer.png"},
        "AMETHYST_AUBERGINE": {"name": "紫水晶茄子", "image": "relics/amethyst_aubergine.png"},
        "ANCHOR": {"name": "锚", "image": "relics/anchor.png"},
        "ARCANE_SCROLL": {"name": "奥术卷轴", "image": "relics/arcane_scroll.png"},
        "ARCHAIC_TOOTH": {"name": "古老牙齿", "image": "relics/archaic_tooth.png"},
        "ART_OF_WAR": {"name": "孙子兵法", "image": "relics/art_of_war.png"},
        "ASTROLABE": {"name": "星盘", "image": "relics/astrolabe.png"},
        "BAG_OF_MARBLES": {"name": "弹珠袋", "image": "relics/bag_of_marbles.png"},
        "BAG_OF_PREPARATION": {"name": "准备背包", "image": "relics/bag_of_preparation.png"},
        "BEATING_REMNANT": {"name": "律动残余", "image": "relics/beating_remnant.png"},
        "BEAUTIFUL_BRACELET": {"name": "华美手镯", "image": "relics/beautiful_bracelet.png"},
        "BELLOWS": {"name": "风箱", "image": "relics/bellows.png"},
        "BELT_BUCKLE": {"name": "腰带扣", "image": "relics/belt_buckle.png"},
        "BIG_HAT": {"name": "大帽子", "image": "relics/big_hat.png"},
        "BIG_MUSHROOM": {"name": "大蘑菇", "image": "relics/big_mushroom.png"},
        "BIIIG_HUG": {"name": "大～抱抱", "image": "relics/biiig_hug.png"},
        "BING_BONG": {"name": "冰梆", "image": "relics/bing_bong.png"},
        "BLACK_BLOOD": {"name": "黑暗之血", "image": "relics/black_blood.png"},
        "BLACK_STAR": {"name": "黑星", "image": "relics/black_star.png"},
        "BLESSED_ANTLER": {"name": "赐福鹿角", "image": "relics/blessed_antler.png"},
        "BLOOD_SOAKED_ROSE": {"name": "血染玫瑰", "image": "relics/blood_soaked_rose.png"},
        "BLOOD_VIAL": {"name": "小血瓶", "image": "relics/blood_vial.png"},
        "BONE_FLUTE": {"name": "骨笛", "image": "relics/bone_flute.png"},
        "BONE_TEA": {"name": "骨茶", "image": "relics/bone_tea.png"},
        "BOOKMARK": {"name": "书签", "image": "relics/bookmark.png"},
        "BOOK_OF_FIVE_RINGS": {"name": "五轮书", "image": "relics/book_of_five_rings.png"},
        "BOOK_REPAIR_KNIFE": {"name": "修书小刀", "image": "relics/book_repair_knife.png"},
        "BOOMING_CONCH": {"name": "轰鸣海螺", "image": "relics/booming_conch.png"},
        "BOUND_PHYLACTERY": {"name": "缚魂命匣", "image": "relics/bound_phylactery.png"},
        "BOWLER_HAT": {"name": "圆顶礼帽", "image": "relics/bowler_hat.png"},
        "BREAD": {"name": "面包", "image": "relics/bread.png"},
        "BRILLIANT_SCARF": {"name": "艳丽围巾", "image": "relics/brilliant_scarf.png"},
        "BRIMSTONE": {"name": "硫磺", "image": "relics/brimstone.png"},
        "BRONZE_SCALES": {"name": "铜质鳞片", "image": "relics/bronze_scales.png"},
        "BURNING_BLOOD": {"name": "燃烧之血", "image": "relics/burning_blood.png"},
        "BURNING_STICKS": {"name": "燃烧木棍", "image": "relics/burning_sticks.png"},
        "BYRDPIP": {"name": "异鸟宝宝", "image": "relics/byrdpip.png"},
        "CALLING_BELL": {"name": "召唤铃铛", "image": "relics/calling_bell.png"},
        "CANDELABRA": {"name": "烛台", "image": "relics/candelabra.png"},
        "CAPTAINS_WHEEL": {"name": "舵盘", "image": "relics/captains_wheel.png"},
        "CAULDRON": {"name": "大锅", "image": "relics/cauldron.png"},
        "CENTENNIAL_PUZZLE": {"name": "百年积木", "image": "relics/centennial_puzzle.png"},
        "CHANDELIER": {"name": "吊灯", "image": "relics/chandelier.png"},
        "CHARONS_ASHES": {"name": "卡戎之灰", "image": "relics/charons_ashes.png"},
        "CHEMICAL_X": {"name": "化学物X", "image": "relics/chemical_x.png"},
        "CHOICES_PARADOX": {"name": "选择悖论", "image": "relics/choices_paradox.png"},
        "CHOSEN_CHEESE": {"name": "天选芝士", "image": "relics/chosen_cheese.png"},
        "CIRCLET": {"name": "头环", "image": "relics/circlet.png"},
        "CLAWS": {"name": "利爪", "image": "relics/claws.png"},
        "CLOAK_CLASP": {"name": "斗篷扣", "image": "relics/cloak_clasp.png"},
        "CRACKED_CORE": {"name": "破损核心", "image": "relics/cracked_core.png"},
        "CROSSBOW": {"name": "十字弓", "image": "relics/crossbow.png"},
        "CURSED_PEARL": {"name": "诅咒珍珠", "image": "relics/cursed_pearl.png"},
        "DARKSTONE_PERIAPT": {"name": "黑石护符", "image": "relics/darkstone_periapt.png"},
        "DATA_DISK": {"name": "数据磁盘", "image": "relics/data_disk.png"},
        "DAUGHTER_OF_THE_WIND": {"name": "风的女儿", "image": "relics/daughter_of_the_wind.png"},
        "DELICATE_FROND": {"name": "娇嫩蕨草", "image": "relics/delicate_frond.png"},
        "DEMON_TONGUE": {"name": "恶魔之舌", "image": "relics/demon_tongue.png"},
        "DIAMOND_DIADEM": {"name": "钻石头冠", "image": "relics/diamond_diadem.png"},
        "DINGY_RUG": {"name": "肮脏地毯", "image": "relics/dingy_rug.png"},
        "DISTINGUISHED_CAPE": {"name": "卓越斗篷", "image": "relics/distinguished_cape.png"},
        "DIVINE_DESTINY": {"name": "天命所归", "image": "relics/divine_destiny.png"},
        "DIVINE_RIGHT": {"name": "天赋君权", "image": "relics/divine_right.png"},
        "DOLLYS_MIRROR": {"name": "多利之镜", "image": "relics/dollys_mirror.png"},
        "DRAGON_FRUIT": {"name": "火龙果", "image": "relics/dragon_fruit.png"},
        "DREAM_CATCHER": {"name": "捕梦网", "image": "relics/dream_catcher.png"},
        "DRIFTWOOD": {"name": "浮木", "image": "relics/driftwood.png"},
        "DUSTY_TOME": {"name": "尘封魔典", "image": "relics/dusty_tome.png"},
        "ECTOPLASM": {"name": "灵体外质", "image": "relics/ectoplasm.png"},
        "ELECTRIC_SHRYMP": {"name": "放电异虾", "image": "relics/electric_shrymp.png"},
        "EMBER_TEA": {"name": "余烬茶", "image": "relics/ember_tea.png"},
        "EMOTION_CHIP": {"name": "情感芯片", "image": "relics/emotion_chip.png"},
        "EMPTY_CAGE": {"name": "空鸟笼", "image": "relics/empty_cage.png"},
        "ETERNAL_FEATHER": {"name": "永恒羽毛", "image": "relics/eternal_feather.png"},
        "FAKE_ANCHOR": {"name": "锚？？？", "image": "relics/fake_anchor.png"},
        "FAKE_BLOOD_VIAL": {"name": "小血瓶？？？", "image": "relics/fake_blood_vial.png"},
        "FAKE_HAPPY_FLOWER": {"name": "开心小花？？？", "image": "relics/fake_happy_flower.png"},
        "FAKE_LEES_WAFFLE": {"name": "李家华夫饼？？？", "image": "relics/fake_lees_waffle.png"},
        "FAKE_MANGO": {"name": "芒果？？？", "image": "relics/fake_mango.png"},
        "FAKE_MERCHANTS_RUG": {"name": "商人的地毯？？？", "image": "relics/fake_merchants_rug.png"},
        "FAKE_ORICHALCUM": {"name": "奥利哈钢？？？", "image": "relics/fake_orichalcum.png"},
        "FAKE_SNECKO_EYE": {"name": "异蛇之眼？？？", "image": "relics/fake_snecko_eye.png"},
        "FAKE_STRIKE_DUMMY": {"name": "打击木偶？？？", "image": "relics/fake_strike_dummy.png"},
        "FAKE_VENERABLE_TEA_SET": {"name": "古茶具套装？？？", "image": "relics/fake_venerable_tea_set.png"},
        "FENCING_MANUAL": {"name": "击剑指南", "image": "relics/fencing_manual.png"},
        "FESTIVE_POPPER": {"name": "节日拉炮", "image": "relics/festive_popper.png"},
        "FIDDLE": {"name": "小提琴", "image": "relics/fiddle.png"},
        "FORGOTTEN_SOUL": {"name": "遗忘之魂", "image": "relics/forgotten_soul.png"},
        "FRAGRANT_MUSHROOM": {"name": "芳香蘑菇", "image": "relics/fragrant_mushroom.png"},
        "FRESNEL_LENS": {"name": "菲涅耳透镜", "image": "relics/fresnel_lens.png"},
        "FROZEN_EGG": {"name": "冻结之蛋", "image": "relics/frozen_egg.png"},
        "FUNERARY_MASK": {"name": "葬礼面具", "image": "relics/funerary_mask.png"},
        "FUR_COAT": {"name": "皮草大衣", "image": "relics/fur_coat.png"},
        "GALACTIC_DUST": {"name": "星系尘埃", "image": "relics/galactic_dust.png"},
        "GAMBLING_CHIP": {"name": "赌博筹码", "image": "relics/gambling_chip.png"},
        "GAME_PIECE": {"name": "棋子", "image": "relics/game_piece.png"},
        "GHOST_SEED": {"name": "幽灵种子", "image": "relics/ghost_seed.png"},
        "GIRYA": {"name": "壶铃", "image": "relics/girya.png"},
        "GLASS_EYE": {"name": "玻璃眼珠", "image": "relics/glass_eye.png"},
        "GLITTER": {"name": "亮片", "image": "relics/glitter.png"},
        "GNARLED_HAMMER": {"name": "扭曲锤子", "image": "relics/gnarled_hammer.png"},
        "GOLDEN_COMPASS": {"name": "黄金罗盘", "image": "relics/golden_compass.png"},
        "GOLDEN_PEARL": {"name": "金色珍珠", "image": "relics/golden_pearl.png"},
        "GOLD_PLATED_CABLES": {"name": "镀金缆线", "image": "relics/gold_plated_cables.png"},
        "GORGET": {"name": "护喉甲", "image": "relics/gorget.png"},
        "GREMLIN_HORN": {"name": "地精之角", "image": "relics/gremlin_horn.png"},
        "HAND_DRILL": {"name": "手钻", "image": "relics/hand_drill.png"},
        "HAPPY_FLOWER": {"name": "开心小花", "image": "relics/happy_flower.png"},
        "HELICAL_DART": {"name": "螺线飞镖", "image": "relics/helical_dart.png"},
        "HISTORY_COURSE": {"name": "历史课", "image": "relics/history_course.png"},
        "HORN_CLEAT": {"name": "船夹板", "image": "relics/horn_cleat.png"},
        "ICE_CREAM": {"name": "冰淇淋", "image": "relics/ice_cream.png"},
        "INFUSED_CORE": {"name": "注能核心", "image": "relics/infused_core.png"},
        "INTIMIDATING_HELMET": {"name": "骇人头盔", "image": "relics/intimidating_helmet.png"},
        "IRON_CLUB": {"name": "铁棒", "image": "relics/iron_club.png"},
        "IVORY_TILE": {"name": "象牙麻将牌", "image": "relics/ivory_tile.png"},
        "JEWELED_MASK": {"name": "宝石面具", "image": "relics/jeweled_mask.png"},
        "JEWELRY_BOX": {"name": "珠宝盒", "image": "relics/jewelry_box.png"},
        "JOSS_PAPER": {"name": "金纸", "image": "relics/joss_paper.png"},
        "JUZU_BRACELET": {"name": "佛珠手链", "image": "relics/juzu_bracelet.png"},
        "KIFUDA": {"name": "木札", "image": "relics/kifuda.png"},
        "KUNAI": {"name": "苦无", "image": "relics/kunai.png"},
        "KUSARIGAMA": {"name": "锁镰", "image": "relics/kusarigama.png"},
        "LANTERN": {"name": "灯笼", "image": "relics/lantern.png"},
        "LARGE_CAPSULE": {"name": "巨大扭蛋", "image": "relics/large_capsule.png"},
        "LASTING_CANDY": {"name": "吃不完的糖", "image": "relics/lasting_candy.png"},
        "LAVA_LAMP": {"name": "熔岩灯", "image": "relics/lava_lamp.png"},
        "LAVA_ROCK": {"name": "熔岩石", "image": "relics/lava_rock.png"},
        "LEAD_PAPERWEIGHT": {"name": "铅制镇纸", "image": "relics/lead_paperweight.png"},
        "LEAFY_POULTICE": {"name": "树叶药膏", "image": "relics/leafy_poultice.png"},
        "LEES_WAFFLE": {"name": "李家华夫饼", "image": "relics/lees_waffle.png"},
        "LETTER_OPENER": {"name": "开信刀", "image": "relics/letter_opener.png"},
        "LIZARD_TAIL": {"name": "蜥蜴尾巴", "image": "relics/lizard_tail.png"},
        "LOOMING_FRUIT": {"name": "布质果实", "image": "relics/looming_fruit.png"},
        "LORDS_PARASOL": {"name": "领主阳伞", "image": "relics/lords_parasol.png"},
        "LOST_COFFER": {"name": "失物盒", "image": "relics/lost_coffer.png"},
        "LOST_WISP": {"name": "迷失鬼火", "image": "relics/lost_wisp.png"},
        "LUCKY_FYSH": {"name": "招财异鱼", "image": "relics/lucky_fysh.png"},
        "LUNAR_PASTRY": {"name": "月亮糕点", "image": "relics/lunar_pastry.png"},
        "MANGO": {"name": "芒果", "image": "relics/mango.png"},
        "MASSIVE_SCROLL": {"name": "巨大卷轴", "image": "relics/massive_scroll.png"},
        "MAW_BANK": {"name": "巨口储蓄罐", "image": "relics/maw_bank.png"},
        "MEAL_TICKET": {"name": "餐券", "image": "relics/meal_ticket.png"},
        "MEAT_CLEAVER": {"name": "切肉刀", "image": "relics/meat_cleaver.png"},
        "MEAT_ON_THE_BONE": {"name": "带骨肉", "image": "relics/meat_on_the_bone.png"},
        "MEMBERSHIP_CARD": {"name": "会员卡", "image": "relics/membership_card.png"},
        "MERCURY_HOURGLASS": {"name": "水银沙漏", "image": "relics/mercury_hourglass.png"},
        "METRONOME": {"name": "节拍器", "image": "relics/metronome.png"},
        "MINIATURE_CANNON": {"name": "微型大炮", "image": "relics/miniature_cannon.png"},
        "MINIATURE_TENT": {"name": "微型帐篷", "image": "relics/miniature_tent.png"},
        "MINI_REGENT": {"name": "迷你储君", "image": "relics/mini_regent.png"},
        "MOLTEN_EGG": {"name": "熔火之蛋", "image": "relics/molten_egg.png"},
        "MR_STRUGGLES": {"name": "挣扎先生", "image": "relics/mr_struggles.png"},
        "MUMMIFIED_HAND": {"name": "干瘪之手", "image": "relics/mummified_hand.png"},
        "MUSIC_BOX": {"name": "音乐盒", "image": "relics/music_box.png"},
        "MYSTIC_LIGHTER": {"name": "神秘打火机", "image": "relics/mystic_lighter.png"},
        "NEOWS_TORMENT": {"name": "涅奥的苦痛", "image": "relics/neows_torment.png"},
        "NEW_LEAF": {"name": "新叶", "image": "relics/new_leaf.png"},
        "NINJA_SCROLL": {"name": "忍术卷轴", "image": "relics/ninja_scroll.png"},
        "NUNCHAKU": {"name": "双截棍", "image": "relics/nunchaku.png"},
        "NUTRITIOUS_OYSTER": {"name": "营养牡蛎", "image": "relics/nutritious_oyster.png"},
        "NUTRITIOUS_SOUP": {"name": "营养汤", "image": "relics/nutritious_soup.png"},
        "ODDLY_SMOOTH_STONE": {"name": "意外光滑的石头", "image": "relics/oddly_smooth_stone.png"},
        "OLD_COIN": {"name": "古钱币", "image": "relics/old_coin.png"},
        "ORANGE_DOUGH": {"name": "橙色团块", "image": "relics/orange_dough.png"},
        "ORICHALCUM": {"name": "奥利哈钢", "image": "relics/orichalcum.png"},
        "ORNAMENTAL_FAN": {"name": "精致折扇", "image": "relics/ornamental_fan.png"},
        "ORRERY": {"name": "星系仪", "image": "relics/orrery.png"},
        "PAELS_BLOOD": {"name": "佩尔之血", "image": "relics/paels_blood.png"},
        "PAELS_CLAW": {"name": "佩尔之爪", "image": "relics/paels_claw.png"},
        "PAELS_EYE": {"name": "佩尔之眼", "image": "relics/paels_eye.png"},
        "PAELS_FLESH": {"name": "佩尔之肉", "image": "relics/paels_flesh.png"},
        "PAELS_GROWTH": {"name": "佩尔的增生组织", "image": "relics/paels_growth.png"},
        "PAELS_HORN": {"name": "佩尔之角", "image": "relics/paels_horn.png"},
        "PAELS_LEGION": {"name": "佩尔的士兵", "image": "relics/paels_legion.png"},
        "PAELS_TEARS": {"name": "佩尔之泪", "image": "relics/paels_tears.png"},
        "PAELS_TOOTH": {"name": "佩尔之牙", "image": "relics/paels_tooth.png"},
        "PAELS_WING": {"name": "佩尔之翼", "image": "relics/paels_wing.png"},
        "PANDORAS_BOX": {"name": "潘多拉魔盒", "image": "relics/pandoras_box.png"},
        "PANTOGRAPH": {"name": "缩放仪", "image": "relics/pantograph.png"},
        "PAPER_KRANE": {"name": "纸鹤", "image": "relics/paper_krane.png"},
        "PAPER_PHROG": {"name": "纸蛙", "image": "relics/paper_phrog.png"},
        "PARRYING_SHIELD": {"name": "招架盾", "image": "relics/parrying_shield.png"},
        "PEAR": {"name": "梨子", "image": "relics/pear.png"},
        "PENDULUM": {"name": "摆动球", "image": "relics/pendulum.png"},
        "PEN_NIB": {"name": "钢笔尖", "image": "relics/pen_nib.png"},
        "PERMAFROST": {"name": "永冻冰晶", "image": "relics/permafrost.png"},
        "PETRIFIED_TOAD": {"name": "石化蟾蜍", "image": "relics/petrified_toad.png"},
        "PHILOSOPHERS_STONE": {"name": "贤者之石", "image": "relics/philosophers_stone.png"},
        "PHYLACTERY_UNBOUND": {"name": "无界命匣", "image": "relics/phylactery_unbound.png"},
        "PLANISPHERE": {"name": "活动星图", "image": "relics/planisphere.png"},
        "POCKETWATCH": {"name": "怀表", "image": "relics/pocketwatch.png"},
        "POLLINOUS_CORE": {"name": "花粉核心", "image": "relics/pollinous_core.png"},
        "POMANDER": {"name": "橙型香盒", "image": "relics/pomander.png"},
        "POTION_BELT": {"name": "药水腰带", "image": "relics/potion_belt.png"},
        "POWER_CELL": {"name": "能量电池", "image": "relics/power_cell.png"},
        "PRAYER_WHEEL": {"name": "转经轮", "image": "relics/prayer_wheel.png"},
        "PRECARIOUS_SHEARS": {"name": "松动羊毛剪", "image": "relics/precarious_shears.png"},
        "PRECISE_SCISSORS": {"name": "精准剪刀", "image": "relics/precise_scissors.png"},
        "PRESERVED_FOG": {"name": "腌制活雾", "image": "relics/preserved_fog.png"},
        "PRISMATIC_GEM": {"name": "棱彩宝石", "image": "relics/prismatic_gem.png"},
        "PUMPKIN_CANDLE": {"name": "南瓜蜡烛", "image": "relics/pumpkin_candle.png"},
        "PUNCH_DAGGER": {"name": "拳刃", "image": "relics/punch_dagger.png"},
        "RADIANT_PEARL": {"name": "发光珍珠", "image": "relics/radiant_pearl.png"},
        "RAINBOW_RING": {"name": "彩虹戒指", "image": "relics/rainbow_ring.png"},
        "RAZOR_TOOTH": {"name": "剃刀牙", "image": "relics/razor_tooth.png"},
        "RED_MASK": {"name": "红面具", "image": "relics/red_mask.png"},
        "RED_SKULL": {"name": "红头骨", "image": "relics/red_skull.png"},
        "REGALITE": {"name": "君王矿石", "image": "relics/regalite.png"},
        "REGAL_PILLOW": {"name": "皇家枕头", "image": "relics/regal_pillow.png"},
        "REPTILE_TRINKET": {"name": "爬行动物饰品", "image": "relics/reptile_trinket.png"},
        "RINGING_TRIANGLE": {"name": "三角铃鼓", "image": "relics/ringing_triangle.png"},
        "RING_OF_THE_DRAKE": {"name": "长蛇戒指", "image": "relics/ring_of_the_drake.png"},
        "RING_OF_THE_SNAKE": {"name": "蛇之戒指", "image": "relics/ring_of_the_snake.png"},
        "RIPPLE_BASIN": {"name": "波纹水盆", "image": "relics/ripple_basin.png"},
        "ROYAL_POISON": {"name": "王室猛毒", "image": "relics/royal_poison.png"},
        "ROYAL_STAMP": {"name": "王室印章", "image": "relics/royal_stamp.png"},
        "RUINED_HELMET": {"name": "损毁头盔", "image": "relics/ruined_helmet.png"},
        "RUNIC_CAPACITOR": {"name": "符文电容器", "image": "relics/runic_capacitor.png"},
        "RUNIC_PYRAMID": {"name": "符文金字塔", "image": "relics/runic_pyramid.png"},
        "SAI": {"name": "钗", "image": "relics/sai.png"},
        "SAND_CASTLE": {"name": "沙堡", "image": "relics/sand_castle.png"},
        "SCREAMING_FLAGON": {"name": "尖叫酒壶", "image": "relics/screaming_flagon.png"},
        "SCROLL_BOXES": {"name": "卷轴箱", "image": "relics/scroll_boxes.png"},
        "SEAL_OF_GOLD": {"name": "黄金印", "image": "relics/seal_of_gold.png"},
        "SEA_GLASS": {"name": "海玻璃", "image": "relics/sea_glass.png"},
        "SELF_FORMING_CLAY": {"name": "自成型黏土", "image": "relics/self_forming_clay.png"},
        "SERE_TALON": {"name": "原初之爪", "image": "relics/sere_talon.png"},
        "SHOVEL": {"name": "铲子", "image": "relics/shovel.png"},
        "SHURIKEN": {"name": "手里剑", "image": "relics/shuriken.png"},
        "SIGNET_RING": {"name": "图章戒指", "image": "relics/signet_ring.png"},
        "SILVER_CRUCIBLE": {"name": "白银熔炉", "image": "relics/silver_crucible.png"},
        "SLING_OF_COURAGE": {"name": "勇气投石索", "image": "relics/sling_of_courage.png"},
        "SMALL_CAPSULE": {"name": "小型扭蛋", "image": "relics/small_capsule.png"},
        "SNECKO_EYE": {"name": "异蛇之眼", "image": "relics/snecko_eye.png"},
        "SNECKO_SKULL": {"name": "异蛇头骨", "image": "relics/snecko_skull.png"},
        "SOZU": {"name": "添水", "image": "relics/sozu.png"},
        "SPARKLING_ROUGE": {"name": "闪亮口红", "image": "relics/sparkling_rouge.png"},
        "SPIKED_GAUNTLETS": {"name": "带刺手甲", "image": "relics/spiked_gauntlets.png"},
        "STONE_CALENDAR": {"name": "历石", "image": "relics/stone_calendar.png"},
        "STONE_CRACKER": {"name": "碎石钻", "image": "relics/stone_cracker.png"},
        "STONE_HUMIDIFIER": {"name": "石炉加湿器", "image": "relics/stone_humidifier.png"},
        "STORYBOOK": {"name": "故事书", "image": "relics/storybook.png"},
        "STRAWBERRY": {"name": "草莓", "image": "relics/strawberry.png"},
        "STRIKE_DUMMY": {"name": "打击木偶", "image": "relics/strike_dummy.png"},
        "STURDY_CLAMP": {"name": "坚固钳子", "image": "relics/sturdy_clamp.png"},
        "SWORD_OF_JADE": {"name": "玉之剑", "image": "relics/sword_of_jade.png"},
        "SWORD_OF_STONE": {"name": "石之剑", "image": "relics/sword_of_stone.png"},
        "SYMBIOTIC_VIRUS": {"name": "共生病毒", "image": "relics/symbiotic_virus.png"},
        "TANXS_WHISTLE": {"name": "坦克斯的哨子", "image": "relics/tanxs_whistle.png"},
        "TEA_OF_DISCOURTESY": {"name": "无礼之茶", "image": "relics/tea_of_discourtesy.png"},
        "THE_ABACUS": {"name": "算盘", "image": "relics/the_abacus.png"},
        "THE_BOOT": {"name": "发条靴", "image": "relics/the_boot.png"},
        "THE_COURIER": {"name": "送货员", "image": "relics/the_courier.png"},
        "THROWING_AXE": {"name": "投斧", "image": "relics/throwing_axe.png"},
        "TINGSHA": {"name": "铜钹", "image": "relics/tingsha.png"},
        "TINY_MAILBOX": {"name": "小邮箱", "image": "relics/tiny_mailbox.png"},
        "TOASTY_MITTENS": {"name": "烘焙手套", "image": "relics/toasty_mittens.png"},
        "TOOLBOX": {"name": "工具箱", "image": "relics/toolbox.png"},
        "TOUCH_OF_OROBAS": {"name": "欧洛巴斯之触", "image": "relics/touch_of_orobas.png"},
        "TOUGH_BANDAGES": {"name": "结实绷带", "image": "relics/tough_bandages.png"},
        "TOXIC_EGG": {"name": "毒素之蛋", "image": "relics/toxic_egg.png"},
        "TOY_BOX": {"name": "玩具盒", "image": "relics/toy_box.png"},
        "TRI_BOOMERANG": {"name": "三刃回旋镖", "image": "relics/tri_boomerang.png"},
        "TUNGSTEN_ROD": {"name": "钨合金棍", "image": "relics/tungsten_rod.png"},
        "TUNING_FORK": {"name": "音叉", "image": "relics/tuning_fork.png"},
        "TWISTED_FUNNEL": {"name": "扭曲漏斗", "image": "relics/twisted_funnel.png"},
        "UNCEASING_TOP": {"name": "不休陀螺", "image": "relics/unceasing_top.png"},
        "UNDYING_SIGIL": {"name": "不死符文", "image": "relics/undying_sigil.png"},
        "UNSETTLING_LAMP": {"name": "不安油灯", "image": "relics/unsettling_lamp.png"},
        "VAJRA": {"name": "金刚杵", "image": "relics/vajra.png"},
        "VAKUU_CARD_SELECTOR": {"name": "VakuuCardSelector", "image": ""},
        "VAMBRACE": {"name": "臂甲", "image": "relics/vambrace.png"},
        "VELVET_CHOKER": {"name": "天鹅绒颈圈", "image": "relics/velvet_choker.png"},
        "VENERABLE_TEA_SET": {"name": "古茶具套装", "image": "relics/venerable_tea_set.png"},
        "VERY_HOT_COCOA": {"name": "烫嘴可可", "image": "relics/very_hot_cocoa.png"},
        "VEXING_PUZZLEBOX": {"name": "烦人机关盒", "image": "relics/vexing_puzzlebox.png"},
        "VITRUVIAN_MINION": {"name": "维特鲁威仆从", "image": "relics/vitruvian_minion.png"},
        "WAR_HAMMER": {"name": "战锤", "image": "relics/war_hammer.png"},
        "WAR_PAINT": {"name": "战纹涂料", "image": "relics/war_paint.png"},
        "WHETSTONE": {"name": "磨刀石", "image": "relics/whetstone.png"},
        "WHISPERING_EARRING": {"name": "低语耳环", "image": "relics/whispering_earring.png"},
        "WHITE_BEAST_STATUE": {"name": "白兽雕像", "image": "relics/white_beast_statue.png"},
        "WHITE_STAR": {"name": "白星", "image": "relics/white_star.png"},
        "WING_CHARM": {"name": "羽翼护符", "image": "relics/wing_charm.png"},
        "WONGOS_MYSTERY_TICKET": {"name": "旺购神秘券", "image": "relics/wongos_mystery_ticket.png"},
        "WONGO_CUSTOMER_APPRECIATION_BADGE": {"name": "旺购客户感恩徽章", "image": "relics/wongo_customer_appreciation_badge.png"},
        "YUMMY_COOKIE": {"name": "美味饼干", "image": ""}
    },
    monsters: {
        "ACID_SLIME": "酸液史莱姆",
        "ARCHITECT": "建筑师",
        "ASSASSIN_RUBY_RAIDER": "劫掠者刺客",
        "AWAKENED_ONE": "觉醒者",
        "AXEBOT": "巨斧机器人",
        "AXE_RUBY_RAIDER": "劫掠者斧手",
        "BATTLE_FRIEND_V1": "战斗好伙伴V1.0",
        "BATTLE_FRIEND_V2": "战斗好伙伴V2.0",
        "BATTLE_FRIEND_V3": "战斗好伙伴V3.0",
        "BOOK_OF_STABBING": "扎人书",
        "BOWLBUG_EGG": "盛碗虫（卵）",
        "BOWLBUG_NECTAR": "盛碗虫（蜜）",
        "BOWLBUG_ROCK": "盛碗虫（石）",
        "BOWLBUG_SILK": "盛碗虫（丝）",
        "BRONZE_AUTOMATON": "青铜 automaton",
        "BRUTE_RUBY_RAIDER": "劫掠者暴徒",
        "BYGONE_EFFIGY": "旧日雕像",
        "BYRD": "异鸟",
        "BYRDONIS": "多尼斯异鸟",
        "BYRDPIP": "异鸟宝宝",
        "CALCIFIED_CULTIST": "钙化邪教徒",
        "CANNONEER": "高塔炮手",
        "CENTURION": "百夫长",
        "CEREMONIAL_BEAST": "仪式兽",
        "CHAMP": "冠军",
        "CHOMPER": "啃咬机",
        "CHOSEN": "被选中者",
        "CORPSE_SLUG": "噬尸蛞蝓",
        "CORRUPT_HEART": "腐化之心",
        "CROSSBOW_RUBY_RAIDER": "劫掠者弩手",
        "CRUSHER": "碾碎爪",
        "CUBEX_CONSTRUCT": "立柱构造体",
        "CULTIST": "邪教徒",
        "DAMP_CULTIST": "潮湿邪教徒",
        "DARKLING": "小黑",
        "DECIMILLIPEDE_SEGMENT": "残杀千足虫",
        "DEVOTED_SCULPTOR": "虔诚雕刻师",
        "DONU_DECA": "唐纳和德卡",
        "DOOR": "门扉",
        "DOORMAKER": "门扉缔造者",
        "ENTOMANCER": "蜂群术士",
        "EXOSKELETON": "外骨骼虫",
        "EXPLODER": "爆炸机",
        "EYE_WITH_TEETH": "利齿之眼",
        "FABRICATOR": "组装师",
        "FAT_GREMLIN": "胖地精",
        "FLAIL_KNIGHT": "连枷骑士",
        "FLYCONID": "飞蝇菌子",
        "FOGMOG": "雾菇",
        "FOSSIL_STALKER": "化石追踪者",
        "FROG_KNIGHT": "青蛙骑士",
        "FROG_KNIGHT_2": "青蛙骑士",
        "FUNGUS_BEAST": "真菌兽",
        "FUZZY_WURM_CRAWLER": "毛绒伏地虫",
        "GAS_BOMB": "气态炸弹",
        "GIANT": "巨人",
        "GIANT_HEAD": "大头",
        "GLOBE_HEAD": "电球头",
        "GREMLIN": "地精",
        "GREMLIN_LEADER": "地精首领",
        "GREMLIN_MERC": "地精佣兵",
        "GREMLIN_NOB": "地精首领",
        "GUARDBOT": "守护机器人",
        "HAUNTED_SHIP": "幽灵船",
        "HEXAGHOST": "六火亡魂",
        "HUNTER_KILLER": "猎人杀手",
        "INFESTED_PRISM": "感染棱柱",
        "INKLET": "墨宝",
        "JAW_WORM": "钳虫",
        "KIN_FOLLOWER": "同族信徒",
        "KIN_PRIEST": "同族神官",
        "KNOWLEDGE_DEMON": "知识恶魔",
        "LAGAVULIN": "拉格瓦林",
        "LAGAVULIN_MATRIARCH": "乐加维林族母",
        "LEAF_SLIME_M": "树叶史莱姆（中）",
        "LEAF_SLIME_S": "树叶史莱姆（小）",
        "LIVING_FOG": "活雾",
        "LIVING_SHIELD": "活体盾",
        "LOUSE": "虱虫",
        "LOUSE_PROGENITOR": "虱虫之祖",
        "MAGI_KNIGHT": "魔法骑士",
        "MAW": "大嘴",
        "MAWLER": "蛮兽",
        "MECHA_KNIGHT": "机甲骑士",
        "MYSTIC": "神秘术士",
        "MYTE": "异螨",
        "NEMESIS": "天罚",
        "NIBBIT": "小啃兽",
        "NOISEBOT": "噪音机器人",
        "ORB_WALKER": "球体行者",
        "OSTY": "奥斯提",
        "OVICOPTER": "直飞产卵虫",
        "OWL_MAGISTRATE": "猫头鹰法官",
        "PAELS_LEGION": "佩尔的士兵",
        "PARAFRIGHT": "寄生惧魔",
        "PHANTASMAL_GARDENER": "花园幽灵鳗",
        "PHROG_PARASITE": "异蛙寄生虫",
        "PLANT": "植物",
        "PUNCH_CONSTRUCT": "拳击构装体",
        "QUEEN": "女王",
        "REPTOMANCER": "养 repto 者",
        "REPULSOR": "反击机",
        "ROCKET": "火箭",
        "SCROLL_OF_BITING": "咬人卷轴",
        "SEAPUNK": "海洋混混",
        "SENTRY": "哨卫",
        "SEWER_CLAM": "下水道蚌",
        "SHELLED_PARASITE": "带壳寄生虫",
        "SHRINKER_BEETLE": "缩小甲虫",
        "SKULKING_COLONY": "鬼祟珊瑚群",
        "SLIME": "史莱姆",
        "SLIMED_BERSERKER": "史莱姆狂战士",
        "SLIME_BOSS": "史莱姆Boss",
        "SLITHERING_STRANGLER": "蛇行扼杀者",
        "SLUDGE_SPINNER": "淤泥旋螺",
        "SLUMBERING_BEETLE": "熟睡甲虫",
        "SNAKE": "巨蛇",
        "SNAKE_PLANT": "蛇草",
        "SNAPPING_JAXFRUIT": "闪光贾克斯果",
        "SNEAKY_GREMLIN": "卑鄙地精",
        "SNECKO": "异蛇",
        "SOUL_FYSH": "灵魂异鱼",
        "SOUL_NEXUS": "灵魂枢纽",
        "SPECTRAL_KNIGHT": "幽灵骑士",
        "SPHERIC_GUARDIAN": "圆球守护者",
        "SPIDER": "蜘蛛",
        "SPIKER": "尖刺机",
        "SPIKE_SLIME": "尖刺史莱姆",
        "SPINY_TOAD": "棘刺蟾蜍",
        "STABBOT": "戳刺机器人",
        "TASKMASTER": "监工",
        "TASKMASTER_2": "高级监工",
        "TERROR_EEL": "骇鳗",
        "TEST_SUBJECT": "实验体 #C{Count}",
        "THE_ADVERSARY_MK_ONE": "对手1型",
        "THE_ADVERSARY_MK_THREE": "对手3型",
        "THE_ADVERSARY_MK_TWO": "对手2型",
        "THE_FORGOTTEN": "遗忘之物",
        "THE_GUARDIAN": "守护者",
        "THE_INSATIABLE": "无厌沙虫",
        "THE_LOST": "失落之物",
        "THE_OBSCURA": "胧光怪",
        "THIEVES": "小偷",
        "THIEVING_HOPPER": "偷窃草蜢",
        "TIME_EATER": "时间吞噬者",
        "TOADPOLE": "蟾蜍蝌蚪",
        "TORCH_HEAD_AMALGAM": "火炬头聚合体",
        "TOUGH_EGG": "结实的卵",
        "TRACKER_RUBY_RAIDER": "劫掠者追踪手",
        "TRANSIENT": "瞬移者",
        "TUNNELER": "地道虫",
        "TURRET_OPERATOR": "高塔炮手",
        "TWIG_SLIME_M": "树枝史莱姆（中）",
        "TWIG_SLIME_S": "树枝史莱姆（小）",
        "TWO_TAILED_RAT": "双尾鼠",
        "VANTOM": "墨影幻灵",
        "VINE_SHAMBLER": "藤蔓蹒跚者",
        "WATERFALL_GIANT": "瀑布巨兽",
        "WOLF": "狼",
        "WRIGGLER": "扭动虫",
        "WRITHING_MASS": "蠕动 mass",
        "ZAPBOT": "电击机器人"
    },
    events: {
        "ABYSSAL_BATHS": "深渊浴场",
        "AMALGAMATOR": "熔合者",
        "AROMA_OF_CHAOS": "混沌芳香",
        "BATTLEWORN_DUMMY": "战痕累累的训练假人",
        "BRAIN_LEECH": "脑蛭",
        "BUGSLAYER": "害虫杀手",
        "BYRDONIS_NEST": "多尼斯异鸟巢",
        "COLORFUL_PHILOSOPHERS": "色彩哲学家",
        "COLOSSAL_FLOWER": "巨大花卉",
        "CRYSTAL_SPHERE": "水晶球",
        "DARV": "达弗",
        "DENSE_VEGETATION": "茂密的植被",
        "DOLL_ROOM": "玩偶室",
        "DOORS_OF_LIGHT_AND_DARK": "光与暗的门扉",
        "DROWNING_BEACON": "淹水灯塔",
        "ENDLESS_CONVEYOR": "无尽传送带",
        "FAKE_MERCHANT": "商人？？？",
        "FIELD_OF_MAN_SIZED_HOLES": "人形洞穴之地",
        "GRAVE_OF_THE_FORGOTTEN": "遗忘之墓",
        "HUNGRY_FOR_MUSHROOMS": "蘑菇饥渴",
        "INFESTED_AUTOMATON": "被寄生的自动机械",
        "JUNGLE_MAZE_ADVENTURE": "丛林迷宫奇遇",
        "LOST_WISP": "迷失鬼火",
        "LUMINOUS_CHOIR": "冷光合唱团",
        "MORPHIC_GROVE": "变形灵林谷",
        "NEOW": "涅奥",
        "NONUPEIPE": "诺奴佩普",
        "OROBAS": "欧洛巴斯",
        "PAEL": "佩尔",
        "POTION_COURIER": "药水快递员",
        "PUNCH_OFF": "重拳出击",
        "RANWID_THE_ELDER": "长者兰伟德",
        "REFLECTIONS": "镜中倒影  影倒中镜",
        "RELIC_TRADER": "遗物交换商",
        "ROOM_FULL_OF_CHEESE": "满屋芝士",
        "ROUND_TEA_PARTY": "圆桌茶会",
        "SAPPHIRE_SEED": "蓝宝石种子",
        "SELF_HELP_BOOK": "自助指南",
        "SLIPPERY_BRIDGE": "滑脚木桥",
        "SPIRALING_WHIRLPOOL": "螺旋漩涡",
        "SPIRIT_GRAFTER": "灵魂嫁接者",
        "STONE_OF_ALL_TIME": "永恒之石",
        "SUNKEN_STATUE": "沉没雕像",
        "SUNKEN_TREASURY": "淹水金库",
        "SYMBIOTE": "共生体",
        "TABLET_OF_TRUTH": "真理石板",
        "TANX": "坦克斯",
        "TEA_MASTER": "茶艺大师",
        "TEZCATARA": "特兹卡塔拉",
        "THE_ARCHITECT": "建筑师",
        "THE_FUTURE_OF_POTIONS": "药水的未来？",
        "THE_LANTERN_KEY": "灯火钥匙",
        "THE_LEGENDS_WERE_TRUE": "传说是真的",
        "THIS_OR_THAT": "这个还是那个？",
        "TINKER_TIME": "打造时间",
        "TRASH_HEAP": "垃圾堆",
        "TRIAL": "审判",
        "UNREST_SITE": "无休之处",
        "VAKUU": "瓦库",
        "WAR_HISTORIAN_REPY": "战史学家 付袭",
        "WATERLOGGED_SCRIPTORIUM": "水漫缮写室",
        "WELCOME_TO_WONGOS": "欢迎来到旺购百货",
        "WELLSPRING": "泉水",
        "WHISPERING_HOLLOW": "低语空谷",
        "WOOD_CARVINGS": "木雕",
        "ZEN_WEAVER": "修禅织网者"
    }
};

// 获取卡牌名称
function getCardName(cardId) {
    if (!cardId) return null;
    if (cardId.startsWith('CARD.')) cardId = cardId.slice(5);
    return GAME_DATA.cards[cardId]?.name || cardId.replace(/_/g, ' ');
}

// 获取卡牌图片 URL
function getCardImage(cardId) {
    if (!cardId) return null;
    if (cardId.startsWith('CARD.')) cardId = cardId.slice(5);
    const card = GAME_DATA.cards[cardId];
    if (card?.image) {
        return `${IMAGE_BASE_URL}/${card.image}`;
    }
    return null;
}

// 获取遗物名称
function getRelicName(relicId) {
    if (!relicId) return null;
    if (relicId.startsWith('RELIC.')) relicId = relicId.slice(6);
    if (GAME_DATA.relics[relicId]) {
        return GAME_DATA.relics[relicId].name;
    }
    const withPrefix = 'RELIC.' + relicId;
    if (GAME_DATA.relics[withPrefix]) {
        return GAME_DATA.relics[withPrefix].name;
    }
    return relicId.replace(/_/g, ' ');
}

// 获取遗物图片 URL
function getRelicImage(relicId) {
    if (!relicId) return null;
    if (relicId.startsWith('RELIC.')) relicId = relicId.slice(6);
    
    const relic = GAME_DATA.relics[relicId] || GAME_DATA.relics['RELIC.' + relicId];
    if (relic?.image) {
        return `${IMAGE_BASE_URL}/${relic.image}`;
    }
    return `${IMAGE_BASE_URL}/relics/${relicId.toLowerCase()}.png`;
}

// 获取怪物名称
function getMonsterName(monsterId) {
    if (!monsterId) return null;
    if (monsterId.startsWith('MONSTER.')) monsterId = monsterId.slice(8);
    if (monsterId.startsWith('ENCOUNTER.')) monsterId = monsterId.slice(10);
    
    const baseId = monsterId.replace(/_(WEAK|STRONG|ELITE|BOSS|NORMAL)$/g, '');
    
    return GAME_DATA.monsters[baseId] || baseId.replace(/_/g, ' ');
}

// 获取怪物图片 URL
function getMonsterImage(monsterId) {
    if (!monsterId) return null;
    if (monsterId.startsWith('MONSTER.')) monsterId = monsterId.slice(8);
    if (monsterId.startsWith('ENCOUNTER.')) monsterId = monsterId.slice(10);
    
    const baseId = monsterId.replace(/_(WEAK|STRONG|ELITE|BOSS|NORMAL)$/g, '');
    
    return `${IMAGE_BASE_URL}/monsters/${baseId.toLowerCase()}.png`;
}

// 获取事件名称
function getEventName(eventId) {
    if (!eventId) return null;
    if (eventId.startsWith('EVENT.')) eventId = eventId.slice(6);
    return GAME_DATA.events[eventId] || eventId.replace(/_/g, ' ');
}
